# action.yml
name: 'Compile TeX Document'
description: 'Compiles a TeX document.'
inputs:
  filename:
    description: 'Name of file'
    required: true
  template:
    description: 'Name of template file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
    - --template=${{ inputs.template }}
    - -o
    - out/${{ inputs.filename }}.pdf
